spring:
  application:
    name: "nikkeDiscordBot"
  datasource:
    url: "${db_url}"
    username: "${db_user}"
    password: "${db_password}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


discord:
  bot:
    token: "${Bot_Token}"